def foo() -> void:
    return

def foo() -> void:  # Error: a function named "foo" already exists
    return
