def foo(self) -> void:  # Error: 'self' cannot be used here
    return
