def foo() -> void:
    return

def foo() -> void:  # Error: a function named 'puts' already exists
    return
